name: Atualizar Dados

on:
  schedule:
    - cron: '0 */6 * * *'  # A cada 6 horas
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install requests

      - name: Executar script
        run: python atualizar.py
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}

      - name: Commit e Push
        run: |
          git config --global user.email "github@blogflixtv.com"
          git config --global user.name "Blogflixtv Bot"
          git add dados.json
          git commit -m "Atualização automática dos dados"
          git push
